export const ADD_INSCRIPTION = "ADD_INSCRIPTION ";
export const GET_INSCRISPTION = "GET_INSCRISPTIONS";
export const DELETE_INSCRIPTION  = "DELETE_INSCRIPTIONS";
export const LOAD_INSCRIPTION = "LOAD_INSCRIPTIONS";
export const FAIL_INSCRIPTION = "FAIL_INSCRIPTION";
export const CLEAR_SUCCESSINSCRI = "CLEAR_SUCCESSINSCRI";
export const CLEAR_ERRORINSCRI = "CLEAR_ERRORINSCRI";